from yast3.core.repositories.mirrors.mirror import Mirror

opensuse_mirrors = [
    Mirror(url='download.opensuse.org/', organization='openSUSE', location='Global', sync_frequency='1h', protocols=['http', 'https']),
    Mirror(url='opensuse.mirror.liquidtelecom.com/', organization='Liquid Telecom', location='Kenya', sync_frequency='1h', protocols=['http', 'https', 'ftp', 'rsync']),
    Mirror(url='mirror.opensuse.mu/', organization='cloud.mu', location='Mauritius', sync_frequency='1h', protocols=['https']),
    Mirror(url='opensuse.ucom.am/', organization='Ucom LLC', location='Armenia', sync_frequency='1h', protocols=['http', 'https', 'ftp', 'rsync']),
    Mirror(url='mirrors.aliyun.com/opensuse/', organization='Alibaba Cloud', location='China', sync_frequency='24h', protocols=['http', 'https']),
    Mirror(url='mirror.nyist.edu.cn/opensuse/', organization='Nanyang Institute of Technology', location='China', sync_frequency='24h', protocols=['http', 'https']),
    Mirror(url='mirror.sjtu.edu.cn/opensuse/', organization='Shanghai Jiao Tong University', location='China', sync_frequency='24h', protocols=['http', 'https', 'rsync']),
    Mirror(url='mirrors.163.com/openSUSE/', organization='NetEase', location='China', sync_frequency='24h', protocols=['http', 'https', 'rsync']),
    Mirror(url='mirrors.bfsu.edu.cn/opensuse/', organization='Beijing Foreign Studies University', location='China', sync_frequency='24h', protocols=['http', 'https', 'rsync']),
    Mirror(url='mirrors.nju.edu.cn/opensuse/', organization='Nanjing University', location='China', sync_frequency='24h', protocols=['http', 'https', 'rsync']),
    Mirror(url='mirrors.tuna.tsinghua.edu.cn/opensuse/', organization='Tsinghua University TUNA', location='China', sync_frequency='24h', protocols=['http', 'https', 'rsync']),
    Mirror(url='mirrors.ustc.edu.cn/opensuse/', organization='University of Science and Technology of China', location='China', sync_frequency='24h', protocols=['http', 'https', 'rsync']),
    Mirror(url='mirrors.zju.edu.cn/opensuse/', organization='Zhejiang University', location='China', sync_frequency='24h', protocols=['http']),
    Mirror(url='mirror.rackspace.hk/openSUSE/', organization='Rackspace Hosting', location='Hong Kong', sync_frequency='1h', protocols=['http']),
    Mirror(url='download.opensuse.id/', organization='Komunitas openSUSE Indonesia', location='Indonesia', sync_frequency='1h', protocols=['http', 'https']),
    Mirror(url='repo.ugm.ac.id/opensuse/', organization='Repo UGM', location='Indonesia', sync_frequency='1h', protocols=['http', 'ftp', 'rsync']),
    Mirror(url='ftp.jaist.ac.jp/pub/Linux/openSUSE/', organization='JAIST', location='Japan', sync_frequency='1h', protocols=['http', 'https', 'ftp', 'rsync']),
    Mirror(url='mirror.hashy0917.net/opensuse/', organization='SDCC', location='Japan', sync_frequency='1h', protocols=['http', 'https', 'rsync']),
    Mirror(url='mirror.kakao.com/opensuse/', organization='Kakao', location='South Korea', sync_frequency='1h', protocols=['http', 'https']),
    Mirror(url='download.nus.edu.sg/mirror/opensuse/', organization='National University of Singapore', location='Singapore', sync_frequency='1h', protocols=['http', 'https', 'rsync']),
    Mirror(url='mirror.freedif.org/opensuse/', organization='Freedif', location='Singapore', sync_frequency='1h', protocols=['http', 'https']),
    Mirror(url='free.nchc.org.tw/opensuse/', organization='NCHC', location='Taiwan', sync_frequency='1h', protocols=['http', 'https', 'rsync']),
    Mirror(url='opensuse-mirror-gce-ap.susecloud.net/', organization='SUSE Linux Products GmbH', location='Taiwan', sync_frequency='1h', protocols=['http']),
    Mirror(url='mirror.dc.uz/opensuse/', organization='Datacenter Uzinfocom', location='Uzbekistan', sync_frequency='1h', protocols=['http', 'https', 'ftp', 'rsync']),
    Mirror(url='mirror.alwyzon.net/opensuse/', organization='Alwyzon', location='Austria', sync_frequency='1h', protocols=['http', 'https', 'rsync']),
    Mirror(url='mirror.easyname.at/opensuse/', organization='Easyname GmbH', location='Austria', sync_frequency='1h', protocols=['http', 'https', 'ftp', 'rsync']),
    Mirror(url='opensuse-mirror-gce-eu.opensu.se/', organization='SUSE Linux Products GmbH', location='Belgium', sync_frequency='1h', protocols=['http', 'rsync']),
    Mirror(url='opensuse.mirror-services.net/pub/', organization='BOINC Team Belgium', location='Belgium', sync_frequency='1h', protocols=['http', 'https', 'ftp', 'rsync']),
    Mirror(url='opensuse.ipacct.com/opensuse/', organization='IPACCT Ltd.', location='Bulgaria', sync_frequency='1h', protocols=['http', 'https', 'rsync']),
    Mirror(url='pkg.adfinis-on-exoscale.ch/opensuse/', organization='Adfinis', location='Switzerland', sync_frequency='1h', protocols=['http', 'https']),
    Mirror(url='pkg.adfinis.com/opensuse/', organization='Adfinis AG', location='Switzerland', sync_frequency='1h', protocols=['http', 'https', 'rsync']),
    Mirror(url='mirror.library.ucy.ac.cy/linux/opensuse/', organization='University of Cyprus', location='Cyprus', sync_frequency='1h', protocols=['http', 'rsync']),
    Mirror(url='ftp.linux.cz/pub/linux/opensuse/', organization='CZLUG', location='Czech', sync_frequency='1h', protocols=['http', 'https', 'ftp', 'rsync']),
    Mirror(url='ftp.sh.cvut.cz/opensuse/', organization='Silicon Hill CTU', location='Czech', sync_frequency='1h', protocols=['http', 'https', 'ftp', 'rsync']),
    Mirror(url='mirror.karneval.cz/pub/linux/opensuse/', organization='Vodafone Czech', location='Czech', sync_frequency='1h', protocols=['https', 'ftp', 'rsync']),
    Mirror(url='ftp.fau.de/opensuse/', organization='Friedrich-Alexander University', location='Germany', sync_frequency='1h', protocols=['http', 'https', 'ftp']),
    Mirror(url='ftp.halifax.rwth-aachen.de/opensuse/', organization='RWTH Aachen University', location='Germany', sync_frequency='1h', protocols=['http', 'https', 'ftp', 'rsync']),
    Mirror(url='ftp.gwdg.de/pub/opensuse/', organization='GWDG', location='Germany', sync_frequency='4h', protocols=['http', 'https', 'ftp', 'rsync']),
    Mirror(url='ftp.rz.uni-wuerzburg.de/linux/opensuse/', organization='University of Wuerzburg', location='Germany', sync_frequency='1h', protocols=['http', 'https', 'ftp', 'rsync']),
    Mirror(url='ftp.tu-chemnitz.de/pub/linux/opensuse/', organization='TU Chemnitz', location='Germany', sync_frequency='1h', protocols=['http', 'https', 'ftp', 'rsync']),
    Mirror(url='ftp.tu-ilmenau.de/mirror/opensuse/', organization='TU Ilmenau', location='Germany', sync_frequency='1h', protocols=['http', 'https', 'ftp', 'rsync']),
    Mirror(url='ftp.uni-bayreuth.de/linux/opensuse/', organization='University of Bayreuth', location='Germany', sync_frequency='1h', protocols=['http', 'https', 'ftp', 'rsync']),
    Mirror(url='ftp.uni-erlangen.de/opensuse/', organization='University of Erlangen', location='Germany', sync_frequency='1h', protocols=['http', 'https', 'ftp', 'rsync']),
    Mirror(url='mirror.dogado.de/opensuse/', organization='Dogado', location='Germany', sync_frequency='1h', protocols=['http', 'https']),
    Mirror(url='mirror1.hs-esslingen.de/pub/Mirrors/ftp.opensuse.org/', organization='HS Esslingen', location='Germany', sync_frequency='1h', protocols=['http', 'https']),
    Mirror(url='opensuse.schlundtech.de/', organization='Schlund Tech', location='Germany', sync_frequency='1h', protocols=['http', 'https']),
    Mirror(url='mirrors.dotsrc.org/opensuse/', organization='dotsrc.org', location='Denmark', sync_frequency='1h', protocols=['http', 'https']),
    Mirror(url='ftp.funet.fi/pub/mirrors/ftp.opensuse.com/pub/opensuse/', organization='FUNET', location='Finland', sync_frequency='1h', protocols=['http', 'https', 'ftp', 'rsync']),
    Mirror(url='mirror.aardsoft.fi/opensuse/', organization='Aardsoft Oy', location='Finland', sync_frequency='1h', protocols=['http', 'https', 'rsync']),
    Mirror(url='fr2.rpmfind.net/linux/opensuse/', organization='rpmfind.net', location='France', sync_frequency='1h', protocols=['http', 'https']),
    Mirror(url='ftp.cc.uoc.gr/mirrors/linux/opensuse/', organization='University of Crete', location='Greece', sync_frequency='1h', protocols=['http', 'https', 'ftp', 'rsync']),
    Mirror(url='opensuse.mirror.garr.it/', organization='GARR', location='Italy', sync_frequency='1h', protocols=['http', 'https']),
    Mirror(url='mirror.rackspace.co.uk/openSUSE/', organization='Rackspace Hosting', location='UK', sync_frequency='1h', protocols=['http', 'https']),
    Mirror(url='mirror.truenetwork.ru/opensuse/', organization='Truenetwork', location='Russia', sync_frequency='1h', protocols=['http', 'https', 'ftp', 'rsync']),
    Mirror(url='mirror.tspu.ru/opensuse/', organization='Tomsk State Pedagogical University', location='Russia', sync_frequency='1h', protocols=['ftp', 'rsync']),
    Mirror(url='mirror.rackspace.com/openSUSE/', organization='Rackspace Hosting', location='USA', sync_frequency='1h', protocols=['http', 'https', 'ftp', 'rsync']),
    Mirror(url='slc-mirror.opensuse.org/', organization='openSUSE', location='USA', sync_frequency='1h', protocols=['https', 'rsync']),
    Mirror(url='www.gtlib.gatech.edu/pub/opensuse/', organization='Georgia Institute of Technology', location='USA', sync_frequency='1h', protocols=['http']),
    Mirror(url='mirror.firstyear.id.au/', organization='William Brown', location='Australia', sync_frequency='1h', protocols=['http', 'https']),
    Mirror(url='mirror-br.opensuse.org/', organization='Tyna Host+SUSE', location='Brazil', sync_frequency='1h', protocols=['http', 'https']),
    Mirror(url='espejito.fder.edu.uy/opensuse/', organization='Universidad de la República', location='Uruguay', sync_frequency='1h', protocols=['http']),
]