from yast3.core.repositories.mirrors.mirror import Mirror

opensuse_mirrors = [
    Mirror(url='download.opensuse.org/', organization='openSUSE', location='Global', sync_frequency='1h', protocols=['http', 'https']),
    Mirror(url='mirrors.aliyun.com/opensuse/', organization='Alibaba Cloud', location='China', sync_frequency='24h', protocols=['http', 'https']),
    Mirror(url='mirrors.163.com/openSUSE/', organization='NetEase', location='China', sync_frequency='24h', protocols=['http', 'https', 'rsync']),
    Mirror(url='mirrors.tuna.tsinghua.edu.cn/opensuse/', organization='Tsinghua University TUNA', location='China', sync_frequency='24h', protocols=['http', 'https', 'rsync']),
    Mirror(url='mirrors.bfsu.edu.cn/opensuse/', organization='Beijing Foreign Studies University', location='China', sync_frequency='24h', protocols=['http', 'https', 'rsync']),
    Mirror(url='mirrors.nju.edu.cn/opensuse/', organization='Nanjing University', location='China', sync_frequency='24h', protocols=['http', 'https', 'rsync']),
    Mirror(url='mirrors.ustc.edu.cn/opensuse/', organization='University of Science and Technology of China', location='China', sync_frequency='24h', protocols=['http', 'https', 'rsync']),
    Mirror(url='mirror.sjtu.edu.cn/opensuse/', organization='Shanghai Jiao Tong University', location='China', sync_frequency='24h', protocols=['http', 'https', 'rsync']),
    Mirror(url='mirror.nyist.edu.cn/opensuse/', organization='Nanyang Institute of Technology', location='China', sync_frequency='24h', protocols=['http']),
    Mirror(url='mirrors.zju.edu.cn/opensuse/', organization='Zhejiang University', location='China', sync_frequency='24h', protocols=['http']),
    Mirror(url='mirror.karneval.cz/pub/linux/opensuse/', organization='Vodafone Czech', location='Czech', sync_frequency='1h', protocols=['https', 'ftp', 'rsync']),
    Mirror(url='ftp.linux.cz/pub/linux/opensuse/', organization='CZLUG', location='Czech', sync_frequency='1h', protocols=['http', 'https', 'ftp', 'rsync']),
    Mirror(url='ftp.sh.cvut.cz/opensuse/', organization='Silicon Hill CTU', location='Czech', sync_frequency='1h', protocols=['http', 'https', 'ftp', 'rsync']),
    Mirror(url='ftp.fau.de/opensuse/', organization='Friedrich-Alexander University', location='Germany', sync_frequency='1h', protocols=['http', 'https', 'ftp']),
    Mirror(url='ftp.halifax.rwth-aachen.de/opensuse/', organization='RWTH Aachen University', location='Germany', sync_frequency='1h', protocols=['http', 'https', 'ftp', 'rsync']),
    Mirror(url='ftp.gwdg.de/pub/opensuse/', organization='GWDG', location='Germany', sync_frequency='4h', protocols=['http', 'https', 'ftp', 'rsync']),
    Mirror(url='mirror.alwyzon.net/opensuse/', organization='Alwyzon', location='Austria', sync_frequency='1h', protocols=['http', 'https', 'rsync']),
    Mirror(url='mirror.easyname.at/opensuse/', organization='Easyname GmbH', location='Austria', sync_frequency='1h', protocols=['http', 'https', 'ftp', 'rsync']),
    Mirror(url='ftp.jaist.ac.jp/pub/Linux/openSUSE/', organization='JAIST', location='Japan', sync_frequency='1h', protocols=['http', 'https', 'ftp', 'rsync']),
    Mirror(url='mirror.kakao.com/opensuse/', organization='Kakao', location='South Korea', sync_frequency='1h', protocols=['http', 'https']),
    Mirror(url='download.nus.edu.sg/mirror/opensuse/', organization='National University of Singapore', location='Singapore', sync_frequency='1h', protocols=['http', 'https', 'rsync']),
    Mirror(url='mirror.freedif.org/opensuse/', organization='Freedif', location='Singapore', sync_frequency='1h', protocols=['http', 'https']),
    Mirror(url='free.nchc.org.tw/opensuse/', organization='NCHC', location='Taiwan', sync_frequency='1h', protocols=['http', 'https', 'rsync']),
    Mirror(url='opensuse.mirror.liquidtelecom.com/', organization='Liquid Telecom', location='Kenya', sync_frequency='1h', protocols=['http', 'https', 'ftp', 'rsync']),
    Mirror(url='opensuse.ucom.am/', organization='Ucom LLC', location='Armenia', sync_frequency='1h', protocols=['http', 'https', 'ftp', 'rsync']),
    Mirror(url='download.opensuse.id/', organization='Komunitas openSUSE Indonesia', location='Indonesia', sync_frequency='1h', protocols=['http', 'https']),
    Mirror(url='repo.ugm.ac.id/opensuse/', organization='Repo UGM', location='Indonesia', sync_frequency='1h', protocols=['http', 'ftp', 'rsync']),
    Mirror(url='mirror.dc.uz/opensuse/', organization='Datacenter Uzinfocom', location='Uzbekistan', sync_frequency='1h', protocols=['http', 'https', 'ftp', 'rsync']),
    Mirror(url='opensuse.ipacct.com/opensuse/', organization='IPACCT Ltd.', location='Bulgaria', sync_frequency='1h', protocols=['http', 'https', 'rsync']),
    Mirror(url='pkg.adfinis.com/opensuse/', organization='Adfinis AG', location='Switzerland', sync_frequency='1h', protocols=['http', 'https', 'rsync']),
]