"""Blacklist of common Android bloatware packages."""

from __future__ import annotations

BLACKLIST = {
    "com.android.chrome": {"name": "Google Chrome", "description": "浏览器", "dangerous": False},
    "com.google.android.youtube": {"name": "YouTube", "description": "视频", "dangerous": False},
    "com.google.android.googlequicksearchbox": {"name": "Google搜索", "description": "搜索引擎", "dangerous": False},
    "com.google.android.apps.maps": {"name": "Google地图", "description": "地图服务", "dangerous": False},
    "com.google.android.apps.photos": {"name": "Google相册", "description": "相册", "dangerous": False},
    "com.google.android.music": {"name": "Google Play音乐", "description": "音乐", "dangerous": False},
    "com.google.android.videos": {"name": "Google Play视频", "description": "视频", "dangerous": False},
    "com.google.android.apps.walletnfcrel": {"name": "Google钱包", "description": "支付", "dangerous": False},
    "com.google.android.apps.docs": {"name": "Google文档", "description": "办公", "dangerous": False},
    "com.google.android.apps.drive": {"name": "Google云端硬盘", "description": "云存储", "dangerous": False},
    "com.google.android.apps.keep": {"name": "Google Keep", "description": "笔记", "dangerous": False},
    "com.google.android.apps.tachyon": {"name": "Google Duo", "description": "视频通话", "dangerous": False},
    "com.google.android.apps.meet": {"name": "Google Meet", "description": "会议", "dangerous": False},
    "com.google.android.calendar": {"name": "Google日历", "description": "日历", "dangerous": False},
    "com.google.android.contacts": {"name": "Google联系人", "description": "联系人", "dangerous": False},
    "com.google.android.deskclock": {"name": "Google时钟", "description": "时钟", "dangerous": False},
    "com.google.android.gm": {"name": "Gmail", "description": "邮件", "dangerous": False},
    "com.google.android.feedback": {"name": "Google反馈", "description": "反馈", "dangerous": False},
    "com.google.android.partnersetup": {"name": "Google合作伙伴设置", "description": "设置", "dangerous": False},
    "com.google.android.setupwizard": {"name": "Google设置向导", "description": "向导", "dangerous": False},
    "com.google.android.syncadapters.contacts": {"name": "Google联系人同步", "description": "同步", "dangerous": False},
    "com.google.android.backuptransport": {"name": "Google备份传输", "description": "备份", "dangerous": False},
    "com.google.android.configupdater": {"name": "Google配置更新", "description": "更新", "dangerous": False},
    "com.google.android.gms.location.history": {"name": "Google位置历史", "description": "位置", "dangerous": False},
    "com.google.android.printservice.recommendation": {"name": "Google打印服务", "description": "打印", "dangerous": False},
    "com.android.wallpaper": {"name": "壁纸", "description": "系统壁纸", "dangerous": False},
    "com.android.wallpaper.livepicker": {"name": "动态壁纸", "description": "壁纸选择", "dangerous": False},
    "com.android.protips": {"name": "使用提示", "description": "使用指南", "dangerous": False},
    "com.android.dreams.basic": {"name": "屏保", "description": "系统屏保", "dangerous": False},
    "com.android.dreams.phototable": {"name": "相册屏保", "description": "屏保", "dangerous": False},
    "com.android.quicksearchbox": {"name": "搜索", "description": "搜索框", "dangerous": False},
    "com.android.wallpapercropper": {"name": "壁纸裁剪", "description": "裁剪", "dangerous": False},
    "com.motorola.android.buacontactadapter": {"name": "摩托罗拉联系人", "description": "联系人", "dangerous": False},
    "com.motorola.android.buainfo": {"name": "摩托罗拉信息", "description": "信息", "dangerous": False},
    "com.motorola.android.buaproviders": {"name": "摩托罗拉提供者", "description": "提供者", "dangerous": False},
    "com.motorola.android.buetoothmce": {"name": "摩托罗拉蓝牙", "description": "蓝牙", "dangerous": False},
    "com.motorola.deepsleepservice": {"name": "摩托罗拉深度睡眠", "description": "睡眠", "dangerous": False},
    "com.motorola.motocare": {"name": "摩托罗拉护理", "description": "护理", "dangerous": False},
    "com.motorola.motosignature.app": {"name": "摩托罗拉签名", "description": "签名", "dangerous": False},
    "com.samsung.android.app.watchmanager": {"name": "三星手表管理", "description": "手表", "dangerous": False},
    "com.samsung.android.app.social": {"name": "三星社交", "description": "社交", "dangerous": False},
    "com.samsung.android.app.spage": {"name": "三星主页", "description": "主页", "dangerous": False},
    "com.samsung.android.app.timeservice": {"name": "三星时间服务", "description": "时间", "dangerous": False},
    "com.samsung.android.bixby": {"name": "Bixby", "description": "语音助手", "dangerous": False},
    "com.samsung.android.bixby.agent": {"name": "Bixby代理", "description": "代理", "dangerous": False},
    "com.samsung.android.bixby.es.globalaction": {"name": "Bixby全局动作", "description": "动作", "dangerous": False},
    "com.samsung.android.bixby.wakeup": {"name": "Bixby唤醒", "description": "唤醒", "dangerous": False},
    "com.samsung.android.bixbyvision.framework": {"name": "Bixby视觉", "description": "视觉", "dangerous": False},
    "com.samsung.android.da.daagent": {"name": "三星数据代理", "description": "数据", "dangerous": False},
    "com.samsung.android.scloud": {"name": "三星云", "description": "云", "dangerous": False},
    "com.samsung.android.sfinder": {"name": "三星搜索", "description": "搜索", "dangerous": False},
    "com.samsung.android.svoice": {"name": "三星语音", "description": "语音", "dangerous": False},
    "com.samsung.android.touchwiz": {"name": "TouchWiz", "description": "UI", "dangerous": False},
    "com.samsung.android.touchwizhome": {"name": "TouchWiz主页", "description": "主页", "dangerous": False},
    "com.samsung.android.wellbeing": {"name": "三星健康", "description": "健康", "dangerous": False},
    "com.htc.android.music": {"name": "HTC音乐", "description": "音乐", "dangerous": False},
    "com.htc.android.weather": {"name": "HTC天气", "description": "天气", "dangerous": False},
    "com.htc.bgp": {"name": "HTC后台服务", "description": "服务", "dangerous": False},
    "com.htc.calendar": {"name": "HTC日历", "description": "日历", "dangerous": False},
    "com.htc.flashlight": {"name": "HTC手电筒", "description": "手电筒", "dangerous": False},
    "com.htc.hTCAlbum": {"name": "HTC相册", "description": "相册", "dangerous": False},
    "com.htc.htccamera": {"name": "HTC相机", "description": "相机", "dangerous": False},
    "com.htc.htccontacts": {"name": "HTC联系人", "description": "联系人", "dangerous": False},
    "com.htc.htcmail": {"name": "HTC邮件", "description": "邮件", "dangerous": False},
    "com.htc.htcsetupwizard": {"name": "HTC设置向导", "description": "向导", "dangerous": False},
    "com.htc.launcher": {"name": "HTC启动器", "description": "启动器", "dangerous": False},
    "com.htc.music": {"name": "HTC音乐", "description": "音乐", "dangerous": False},
    "com.htc.sense.clock": {"name": "HTC时钟", "description": "时钟", "dangerous": False},
    "com.htc.sense.dashboard": {"name": "HTC仪表盘", "description": "仪表盘", "dangerous": False},
    "com.htc.sense.socialnetwork": {"name": "HTC社交网络", "description": "社交", "dangerous": False},
    "com.htc.sense.weather": {"name": "HTC天气", "description": "天气", "dangerous": False},
    "com.asus.album": {"name": "华硕相册", "description": "相册", "dangerous": False},
    "com.asus.calendar": {"name": "华硕日历", "description": "日历", "dangerous": False},
    "com.asus.camera": {"name": "华硕相机", "description": "相机", "dangerous": False},
    "com.asus.cloudstorage": {"name": "华硕云存储", "description": "云", "dangerous": False},
    "com.asus.directlink": {"name": "华硕直连", "description": "连接", "dangerous": False},
    "com.asus.email": {"name": "华硕邮件", "description": "邮件", "dangerous": False},
    "com.asus.filemanager": {"name": "华硕文件管理", "description": "文件", "dangerous": False},
    "com.asus.gallery": {"name": "华硕图库", "description": "图库", "dangerous": False},
    "com.asus.livewidget": {"name": "华硕动态部件", "description": "部件", "dangerous": False},
    "com.asus.mirrorlink": {"name": "华硕镜像链接", "description": "链接", "dangerous": False},
    "com.asus.mycloud": {"name": "华硕我的云", "description": "云", "dangerous": False},
    "com.asus.myguide": {"name": "华硕向导", "description": "向导", "dangerous": False},
    "com.asus.notepad": {"name": "华硕记事本", "description": "笔记", "dangerous": False},
    "com.asus.photo": {"name": "华硕照片", "description": "照片", "dangerous": False},
    "com.asus.smartconnect": {"name": "华硕智能连接", "description": "连接", "dangerous": False},
    "com.asus.soundrecorder": {"name": "华硕录音机", "description": "录音", "dangerous": False},
    "com.asus.stock": {"name": "华硕股票", "description": "股票", "dangerous": False},
    "com.asus.sync": {"name": "华硕同步", "description": "同步", "dangerous": False},
    "com.asus.vibe": {"name": "华硕Vibe", "description": "服务", "dangerous": False},
    "com.asus.wifidirect": {"name": "华硕WiFi直连", "description": "直连", "dangerous": False},
    "com.lge.camera": {"name": "LG相机", "description": "相机", "dangerous": False},
    "com.lge.clock": {"name": "LG时钟", "description": "时钟", "dangerous": False},
    "com.lge.directshare": {"name": "LG直连共享", "description": "共享", "dangerous": False},
    "com.lge.email": {"name": "LG邮件", "description": "邮件", "dangerous": False},
    "com.lge.gallery": {"name": "LG图库", "description": "图库", "dangerous": False},
    "com.lge.launcher": {"name": "LG启动器", "description": "启动器", "dangerous": False},
    "com.lge.lifetimer": {"name": "LG生命周期", "description": "周期", "dangerous": False},
    "com.lge.music": {"name": "LG音乐", "description": "音乐", "dangerous": False},
    "com.lge.musicshare": {"name": "LG音乐共享", "description": "共享", "dangerous": False},
    "com.lge.phonemanager": {"name": "LG手机管理", "description": "管理", "dangerous": False},
    "com.lge.quickmemo": {"name": "LG快速备忘录", "description": "备忘", "dangerous": False},
    "com.lge.smartshare": {"name": "LG智能共享", "description": "共享", "dangerous": False},
    "com.lge.soundrecorder": {"name": "LG录音机", "description": "录音", "dangerous": False},
    "com.lge.tvout": {"name": "LG电视输出", "description": "输出", "dangerous": False},
    "com.lge.weather": {"name": "LG天气", "description": "天气", "dangerous": False},
    "com.lenovo.anyshare.gps": {"name": "联想共享", "description": "共享", "dangerous": False},
    "com.lenovo.android.power": {"name": "联想电源管理", "description": "电源", "dangerous": False},
    "com.lenovo.calendar": {"name": "联想日历", "description": "日历", "dangerous": False},
    "com.lenovo.clock": {"name": "联想时钟", "description": "时钟", "dangerous": False},
    "com.lenovo.commservice": {"name": "联想通信服务", "description": "服务", "dangerous": False},
    "com.lenovo.directshare": {"name": "联想直连", "description": "连接", "dangerous": False},
    "com.lenovo.email": {"name": "联想邮件", "description": "邮件", "dangerous": False},
    "com.lenovo.gallery": {"name": "联想图库", "description": "图库", "dangerous": False},
    "com.lenovo.launcher": {"name": "联想启动器", "description": "启动器", "dangerous": False},
    "com.lenovo.music": {"name": "联想音乐", "description": "音乐", "dangerous": False},
    "com.lenovo.phonemanager": {"name": "联想手机管家", "description": "管家", "dangerous": False},
    "com.lenovo.safe": {"name": "联想安全", "description": "安全", "dangerous": False},
    "com.lenovo.smartcamera": {"name": "联想智能相机", "description": "相机", "dangerous": False},
    "com.lenovo.soundrecorder": {"name": "联想录音机", "description": "录音", "dangerous": False},
    "com.lenovo.sync": {"name": "联想同步", "description": "同步", "dangerous": False},
    "com.lenovo.vcs": {"name": "联想视频通话", "description": "通话", "dangerous": False},
    "com.lenovo.welcome": {"name": "联想欢迎", "description": "欢迎", "dangerous": False},
    "com.zte.service.provider": {"name": "中兴服务", "description": "服务", "dangerous": False},
    "com.zte.systemui.weather": {"name": "中兴天气", "description": "天气", "dangerous": False},
    "com.zte.browser": {"name": "中兴浏览器", "description": "浏览器", "dangerous": False},
    "com.zte.calendar": {"name": "中兴日历", "description": "日历", "dangerous": False},
    "com.zte.clock": {"name": "中兴时钟", "description": "时钟", "dangerous": False},
    "com.zte.email": {"name": "中兴邮件", "description": "邮件", "dangerous": False},
    "com.zte.gallery": {"name": "中兴图库", "description": "图库", "dangerous": False},
    "com.zte.launcher": {"name": "中兴启动器", "description": "启动器", "dangerous": False},
    "com.zte.music": {"name": "中兴音乐", "description": "音乐", "dangerous": False},
    "com.zte.newstoday": {"name": "中兴今日新闻", "description": "新闻", "dangerous": False},
    "com.zte.soundrecorder": {"name": "中兴录音机", "description": "录音", "dangerous": False},
    "com.zte.sync": {"name": "中兴同步", "description": "同步", "dangerous": False},
    "com.huawei.android.pushagent": {"name": "华为推送", "description": "推送", "dangerous": False},
    "com.huawei.browser": {"name": "华为浏览器", "description": "浏览器", "dangerous": False},
    "com.huawei.calendar": {"name": "华为日历", "description": "日历", "dangerous": False},
    "com.huawei.camera": {"name": "华为相机", "description": "相机", "dangerous": False},
    "com.huawei.contacts": {"name": "华为联系人", "description": "联系人", "dangerous": False},
    "com.huawei.drive": {"name": "华为云盘", "description": "云盘", "dangerous": False},
    "com.huawei.email": {"name": "华为邮件", "description": "邮件", "dangerous": False},
    "com.huawei.gamebox": {"name": "华为游戏中心", "description": "游戏", "dangerous": False},
    "com.huawei.health": {"name": "华为运动健康", "description": "健康", "dangerous": False},
    "com.huawei.himovie": {"name": "华为视频", "description": "视频", "dangerous": False},
    "com.huawei.hmusic": {"name": "华为音乐", "description": "音乐", "dangerous": False},
    "com.huawei.mediaplayer": {"name": "华为播放器", "description": "播放", "dangerous": False},
    "com.huawei.mirror": {"name": "华为多屏协同", "description": "协同", "dangerous": False},
    "com.huawei.navi": {"name": "华为地图", "description": "地图", "dangerous": False},
    "com.huawei.phoneservice": {"name": "华为手机服务", "description": "服务", "dangerous": False},
    "com.huawei.soundrecorder": {"name": "华为录音机", "description": "录音", "dangerous": False},
    "com.huawei.systemmanager": {"name": "华为手机管家", "description": "管家", "dangerous": False},
    "com.huawei.wallet": {"name": "华为钱包", "description": "钱包", "dangerous": False},
    "com.huawei.welink": {"name": "华为云会议", "description": "会议", "dangerous": False},
    "com.huawei.android.totemweather": {"name": "华为天气", "description": "天气", "dangerous": False},
    "com.meizu.flyme.browser": {"name": "魅族浏览器", "description": "浏览器", "dangerous": False},
    "com.meizu.flyme.calendar": {"name": "魅族日历", "description": "日历", "dangerous": False},
    "com.meizu.flyme.camera": {"name": "魅族相机", "description": "相机", "dangerous": False},
    "com.meizu.flyme.clock": {"name": "魅族时钟", "description": "时钟", "dangerous": False},
    "com.meizu.flyme.email": {"name": "魅族邮件", "description": "邮件", "dangerous": False},
    "com.meizu.flyme.gallery": {"name": "魅族图库", "description": "图库", "dangerous": False},
    "com.meizu.flyme.music": {"name": "魅族音乐", "description": "音乐", "dangerous": False},
    "com.meizu.flyme.notes": {"name": "魅族便签", "description": "便签", "dangerous": False},
    "com.meizu.flyme.security": {"name": "魅族安全中心", "description": "安全", "dangerous": False},
    "com.meizu.flyme.soundrecorder": {"name": "魅族录音机", "description": "录音", "dangerous": False},
    "com.meizu.flyme.weather": {"name": "魅族天气", "description": "天气", "dangerous": False},
    "com.oppo.browser": {"name": "OPPO浏览器", "description": "浏览器", "dangerous": False},
    "com.oppo.calendar": {"name": "OPPO日历", "description": "日历", "dangerous": False},
    "com.oppo.camera": {"name": "OPPO相机", "description": "相机", "dangerous": False},
    "com.oppo.clock": {"name": "OPPO时钟", "description": "时钟", "dangerous": False},
    "com.oppo.email": {"name": "OPPO邮件", "description": "邮件", "dangerous": False},
    "com.oppo.gallery": {"name": "OPPO相册", "description": "相册", "dangerous": False},
    "com.oppo.music": {"name": "OPPO音乐", "description": "音乐", "dangerous": False},
    "com.oppo.soundrecorder": {"name": "OPPO录音机", "description": "录音", "dangerous": False},
    "com.oppo.weather": {"name": "OPPO天气", "description": "天气", "dangerous": False},
    "com.vivo.browser": {"name": "vivo浏览器", "description": "浏览器", "dangerous": False},
    "com.vivo.calendar": {"name": "vivo日历", "description": "日历", "dangerous": False},
    "com.vivo.camera": {"name": "vivo相机", "description": "相机", "dangerous": False},
    "com.vivo.clock": {"name": "vivo时钟", "description": "时钟", "dangerous": False},
    "com.vivo.email": {"name": "vivo邮件", "description": "邮件", "dangerous": False},
    "com.vivo.gallery": {"name": "vivo图库", "description": "图库", "dangerous": False},
    "com.vivo.music": {"name": "vivo音乐", "description": "音乐", "dangerous": False},
    "com.vivo.notes": {"name": "vivo便签", "description": "便签", "dangerous": False},
    "com.vivo.soundrecorder": {"name": "vivo录音机", "description": "录音", "dangerous": False},
    "com.vivo.weather": {"name": "vivo天气", "description": "天气", "dangerous": False},
    "com.mi.android.globalFileexplorer": {"name": "小米文件管理", "description": "文件", "dangerous": False},
    "com.mi.browser": {"name": "小米浏览器", "description": "浏览器", "dangerous": False},
    "com.mi.calculator": {"name": "小米计算器", "description": "计算", "dangerous": False},
    "com.mi.calendar": {"name": "小米日历", "description": "日历", "dangerous": False},
    "com.mi.carrierdefaultapp": {"name": "小米运营商应用", "description": "应用", "dangerous": False},
    "com.mi.cloudbackup": {"name": "小米云备份", "description": "备份", "dangerous": False},
    "com.mi.cloudservice": {"name": "小米云服务", "description": "云", "dangerous": False},
    "com.mi.duokan": {"name": "多看阅读", "description": "阅读", "dangerous": False},
    "com.mi.email": {"name": "小米邮件", "description": "邮件", "dangerous": False},
    "com.mi.gallery": {"name": "小米图库", "description": "图库", "dangerous": False},
    "com.mi.health": {"name": "小米健康", "description": "健康", "dangerous": False},
    "com.mi.miwallpaper": {"name": "小米壁纸", "description": "壁纸", "dangerous": False},
    "com.mi.music": {"name": "小米音乐", "description": "音乐", "dangerous": False},
    "com.mi.newmidrive": {"name": "小米云盘", "description": "云盘", "dangerous": False},
    "com.mi.notes": {"name": "小米便签", "description": "便签", "dangerous": False},
    "com.mi.shop": {"name": "小米商城", "description": "商城", "dangerous": False},
    "com.mi.soundrecorder": {"name": "小米录音机", "description": "录音", "dangerous": False},
    "com.miui.analytics": {"name": "MIUI分析", "description": "分析", "dangerous": False},
    "com.miui.android.fashiongallery": {"name": "MIUI时尚图库", "description": "图库", "dangerous": False},
    "com.miui.bugreport": {"name": "MIUI反馈", "description": "反馈", "dangerous": False},
    "com.miui.cloudservice": {"name": "MIUI云服务", "description": "云", "dangerous": False},
    "com.miui.compass": {"name": "MIUI指南针", "description": "指南针", "dangerous": False},
    "com.miui.enterprise": {"name": "MIUI企业版", "description": "企业", "dangerous": False},
    "com.miui.freeform": {"name": "MIUI自由窗口", "description": "窗口", "dangerous": False},
    "com.miui.gallery": {"name": "MIUI图库", "description": "图库", "dangerous": False},
    "com.miui.hybrid": {"name": "MIUI混合", "description": "混合", "dangerous": False},
    "com.miui.micloudsync": {"name": "MIUI云同步", "description": "同步", "dangerous": False},
    "com.miui.miwallpaper": {"name": "MIUI壁纸", "description": "壁纸", "dangerous": False},
    "com.miui.msa.global": {"name": "MIUI广告服务", "description": "广告", "dangerous": False},
    "com.miui.screenrecorder": {"name": "MIUI屏幕录制", "description": "录制", "dangerous": False},
    "com.miui.securitycenter": {"name": "MIUI安全中心", "description": "安全", "dangerous": False},
    "com.miui.touchassistant": {"name": "MIUI悬浮球", "description": "悬浮", "dangerous": False},
    "com.miui.virtualsim": {"name": "MIUI虚拟SIM", "description": "SIM", "dangerous": False},
    "com.miui.weather": {"name": "MIUI天气", "description": "天气", "dangerous": False},
    "com.miui.wmsvc": {"name": "MIUI推送", "description": "推送", "dangerous": False},
    "com.facebook.appmanager": {"name": "Facebook应用管理", "description": "管理", "dangerous": False},
    "com.facebook.services": {"name": "Facebook服务", "description": "服务", "dangerous": False},
    "com.facebook.system": {"name": "Facebook系统", "description": "系统", "dangerous": False},
    "com.twitter.android": {"name": "Twitter", "description": "社交", "dangerous": False},
    "com.linkedin.android": {"name": "LinkedIn", "description": "职业", "dangerous": False},
    "com.amazon.kindle": {"name": "Kindle", "description": "阅读", "dangerous": False},
    "com.amazon.mShop.android.shopping": {"name": "亚马逊购物", "description": "购物", "dangerous": False},
    "com.amazon.mp3": {"name": "亚马逊音乐", "description": "音乐", "dangerous": False},
    "com.microsoft.office.excel": {"name": "Excel", "description": "办公", "dangerous": False},
    "com.microsoft.office.powerpoint": {"name": "PowerPoint", "description": "办公", "dangerous": False},
    "com.microsoft.office.word": {"name": "Word", "description": "办公", "dangerous": False},
    "com.microsoft.skydrive": {"name": "OneDrive", "description": "云", "dangerous": False},
    "com.microsoft.windowssearch": {"name": "Windows搜索", "description": "搜索", "dangerous": False},
}


def is_in_blacklist(package_name: str) -> bool:
    return package_name in BLACKLIST


def get_blacklist_info(package_name: str) -> dict[str, str | bool] | None:
    return BLACKLIST.get(package_name)


def get_blacklist_count() -> int:
    return len(BLACKLIST)


def is_dangerous(package_name: str) -> bool:
    info = BLACKLIST.get(package_name)
    return info.get("dangerous", False) if info else False