#!/usr/bin/env python3
"""Script to set NTP servers (requires root)."""

import sys
from pathlib import Path

CHRONYD_CONF = "/etc/chrony.conf"
CHRONYD_D_DIR = "/etc/chrony.d"
CHRONYD_POOL_CONF = "/etc/chrony.d/pool.conf"
NTPD_CONF = "/etc/ntp.conf"


def main():
    servers = sys.argv[1:]
    if not servers:
        print("Usage: set_ntp.py <server1> <server2> ...")
        sys.exit(1)

    try:
        chronyd_d = Path(CHRONYD_D_DIR)
        if chronyd_d.exists() and chronyd_d.is_dir():
            with open(CHRONYD_POOL_CONF, "w") as f:
                f.write("# Generated by YaST3\n")
                for server in servers:
                    f.write(f"pool {server} iburst\n")
        elif Path(CHRONYD_CONF).exists():
            with open(CHRONYD_CONF, "r") as f:
                lines = f.readlines()

            new_lines = []
            for line in lines:
                if not (line.strip().startswith("server ") or line.strip().startswith("pool ")):
                    new_lines.append(line)

            for server in servers:
                new_lines.append(f"server {server}\n")

            with open(CHRONYD_CONF, "w") as f:
                f.writelines(new_lines)
        elif Path(NTPD_CONF).exists():
            with open(NTPD_CONF, "r") as f:
                lines = f.readlines()

            new_lines = []
            for line in lines:
                if not (line.strip().startswith("server ") or line.strip().startswith("pool ")):
                    new_lines.append(line)

            for server in servers:
                new_lines.append(f"server {server}\n")

            with open(NTPD_CONF, "w") as f:
                f.writelines(new_lines)
        else:
            with open(CHRONYD_CONF, "w") as f:
                f.write("# Generated by YaST3\n")
                for server in servers:
                    f.write(f"server {server}\n")

        print("OK")
    except PermissionError:
        print("Permission denied", file=sys.stderr)
        sys.exit(6)
    except Exception as e:
        print(f"Error: {e}", file=sys.stderr)
        sys.exit(1)


if __name__ == "__main__":
    main()